### ISSUE TITLE
Settings toggle is misplaced

### ISSUE THREAD

**Issue by pmatarodrigues** [elementz-ui/elementz#1]
Button to toggle settings is placed almost in the middle of the screen when sidebar is collapsed.

**Browser:** Mozilla Firefox 89.0 (64-bit)
**OS:** Manjaro Linux
**Screen resolution:** 1920x1080

## Screenshots
![image](https://user-images.githubusercontent.com/37421912/122732072-cef27400-d273-11eb-9e96-1bc32c3918c5.png)

## Possible resolution
Set `width:0` to `.ez-theme-maker:not(.active)`

**Comment by el1s7** [comment]
There will be a few cross-browser bugs since I've only tested it on Chrome. 
Looking forward to fixing them, Firefox is a priority. 
Thanks for the first PR!

**Comment by el1s7** [comment]
Fixed by adding '-moz-fit-content'
