### ISSUE TITLE
On row selection the actionable buttons are displayed on far right in the table

### ISSUE THREAD

**Issue by pbdev2605** [elementz-ui/elementz#6]
For tables with large number of columns, if I select a row then the actionable buttons are displayed on far right.
The user would not see these CTAs unless they scroll to extreme right.
How can these be positioned on the left side of the table? or maybe like the select option is displayed irrespective of the scroll position?

![image](https://user-images.githubusercontent.com/85052256/123513355-7293b800-d6aa-11eb-9274-b4647330e774.png)

**Comment by el1s7** [comment]
Fixed (version 2.0.2)
The horizontal scrolling won't affect the bulk actions.
Also fixed some other small things on horizontal scrolling.

Though, for mobile it's recommend you set `onMobile` function.
