### ISSUE TITLE
onSelect and onRowClick does not render custom component

### ISSUE THREAD

**Issue by pbdev2605** [elementz-ui/elementz#7]
Hi,

Thanks for fixing the previous horizontal scrolling. This is a very good and helpful library!

I am not able to make functions such as `onSelect` and `onRowClick` work. I am trying to enable buttons on row click or on single row select as shown below however nothing happens.

```
onSelect={(row, i) => {
          return (
            <Button.Group>
              <Button sm danger reverse icon="delete" /> 
              <Button sm secondary reverse icon="pencil" />
            </Button.Group>
          );
        }}
        onRowClick={(row, i) => {
          return (
            <Button.Group>
              <Button sm danger reverse icon="delete" /> 
              <Button sm secondary reverse icon="pencil" />
            </Button.Group>
          );
        }}
onAction={(row, i, isBulk) => {
          if (!isBulk) {
            return <Button sm simple icon="more-h" className="icon-bold" />;
          } else {
            return (
                <Button sm danger reverse icon="trash" />
            );
          }
        }}
```
If you look at the below image.
1. The `trash ` button is enabled when I select single or multiple rows triggered through onAction. However I expected this to happen when I select more than 1 row (i.e when `isBulk `is true)
2. No buttons are rendered when I select or click a single row

![image](https://user-images.githubusercontent.com/85052256/123521246-18f3b380-d6d3-11eb-9758-128c8543ddc1.png)

Also how can this repo be tested if I fork it locally?

**Comment by el1s7** [comment]
`onSelect` and `onRowClick` are only events and don't render what you return. 

The `onAction` parameters (`row`,`i`) are actually an array of rows and indexes selected. So you can check row.length if more than 1 row is selected.

Currently you can't select a row on click because the selection it's not controlled, but I'm planning on adding controlled states on the next versions.

To test the library locally you can simply `npm run dev`

Make sure you have run `npm install` to install all dependencies first

**Comment by pbdev2605** [comment]
got it! thanks @el1s7 awesome work... looking fwd to controlled states as well

**Comment by el1s7** [comment]
Added controlled states (version 2.0.3)

Check out this example to see how you can select a row on click https://codesandbox.io/s/elementz-controlled-state-d2d7c

View the new API methods at documenation https://elementz.style/#table

Important: Columns, Data and callback function props must be memoized.

Note:  Controlled states is for advanced usage. Data rows are custom indexed in internal functions, meaning you can't directly update states without knowing the row custom indexes.
